### ISSUE TITLE
Themes do not work

### ISSUE THREAD

**Issue by siolag161** [tendenci/tendenci-project-template#1]
Several themes do not work (or maybe i'm doing something wrong over here?)

It gives me this error "TemplateDoesNotExist at /settings/module/theme_editor/#id_theme"

Well, now i'm stuck in the "twenty-thirteen" theme and could not change back. I suspect something wrong with the template page for theme picker.

I'm using the `version 6` using this project template while operating in `Debug` mode

**Comment by eschipul** [comment]
We are working on the themes for Tendenci 6. Currently the ones we have been working with a paid themes from wrapbootstrap.com and as such we can't post them as they aren't cc licensed or gpl. 

The css classes have been standardized on bootstrap 3.3 which is actively in progress. If testing on Tendenci 6, which I do strongly recommend given the interim state I'd recommend using Sublime or a Texteditor to modify the active theme.

On my dev instance I created a new entry in /etc/nginx/sites-enabled to create a /theme/ (singular) folder and added that to my TEMPLATE_DIRS prior to the /themes/ folder. This is a hack and I do apologize, but it should work if you want to get going. It's just really really tedious to update css classes throughout every template. (and I may have edited urls.py to not use the regular expression - I honestly don't recall.

So this is a lame answer. I apologize. Leaving this issue as "open" until we get our stuff together fully which you will know when Tendenci 6 moves up to the origin master. 

If you want to use a theme from wrapbootstrap.com (about $30) then go into the theme editor and at the bottom right there is a "pull down more templates" options. Grab the base.html template and move that into your theme. Then you can specify the sequence of the css loading and all of the power is returned to the designer as it should be. In T5 base.html was in core and the settings in core specified the template read syntax with == so local_settings did += which prevented overriding the base.html template without hacking core. That is a big change in the structure and why the templates had to be moved to the tendenci-project-template - to give you power over all on appearances.

Tendenci will eventually be as flexible as css-zengarden I hope. Not there yet. and they didn't have to worry about responsive design like we do these days. Yet their structure still stands to this day. Pretty impressive stuff.

**Comment by eschipul** [comment]
Please try upgrading to Tendenci 7. It should work now.
https://github.com/tendenci/tendenci/blob/master/docs/source/installation/remote.txt
