### ISSUE TITLE
xhtml2pdf dependency broken

### ISSUE THREAD

**Issue by rob-hills** [tendenci/tendenci-project-template#18]
Following the "Testing" installation instructions at: [readthedocs](https://tendenci.readthedocs.io/en/latest/installation/installation.html), when executing the command:
`pip install tendenci`, the installation reports the following dependency problem:
```
xhtml2pdf 0.2.2 has requirement html5lib>=1.0, but you'll have html5lib 0.9999999 which is incompatible.
```
It appears that the requirements downloaded from PyPi have locked html5lib at 0.9999999 which is causing this problem.

**Comment by goetzk** [comment]
For reference of future visitors; This was also reported as https://github.com/tendenci/tendenci/issues/681 and closed by Jenny in https://github.com/tendenci/tendenci/commit/5ffd6389d53a86e66d76cddf8e7b50f288ac8272 .

Karl.

**Comment by goetzk** [comment]
@jennyq ping on this one

**Comment by jennyq** [comment]
Thanks @goetzk ! I saw this issue was resolved three years ago. Closing it.
