### ISSUE TITLE
Installing Postgresql Error

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci-project-template#2]
I am trying to install tendenci but I am getting 

Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.

**Comment by eschipul** [comment]
Which branch are you on? We are behind on documentation, but if on the "master" branch which is now Tendenci 7 as of this week, then you need to be on Postgres 9.3 with GIS extensions enabled.

**Comment by dco5** [comment]
never mind that one, I just had to install libpq-dev.

But now I am getting:

 running build_ext
    building '_rl_accel' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tmp
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab/src
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons/rl_accel
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c /tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons/rl_accel/_rl_accel.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons/rl_accel/_rl_accel.o
    /tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons/rl_accel/_rl_accel.c:11:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
----------------------------------------
```

  Rolling back uninstall of reportlab
Command "/usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-oEhrNQ/Reportlab/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-M6cTeS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-oEhrNQ/Reportlab

**Comment by dco5** [comment]
I am following the instructions in http://tendenci.readthedocs.org/en/latest/installation/local.html
Which apparently uses the template for tendenci 7

**Comment by eschipul** [comment]
let me double check.... one moment please.

**Comment by eschipul** [comment]
What operating system are you using for the install? Ubuntu 14.04 in a VM I hope? Also the commands you entered prior to getting the error would be hugely helpful.

**Comment by dco5** [comment]
yes that is exactly what I am using.

sudo pip install -r requirements/dev.txt

That was the last command

**Comment by eschipul** [comment]
OK, rebuilt my own computer this week so give me a few to catch up as I need to get the install documentation updated.

That said - we are mostly using dockers lately for deployment although we don't have the code out on .io yet. Are you comfortable with dockers on ubuntu?

**Comment by dco5** [comment]
not really but I could read about it if that is the solution

**Comment by eschipul** [comment]
hold on dockers. when I get a chance in the AM let me walk through the readme and double check for dependencies. it's always dependencies of course...

**Comment by dco5** [comment]
copying src/reportlab/pdfgen/textobject.py -> build/lib.linux-x86_64-2.7/reportlab/pdfgen
    creating build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/figures.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/tableofcontents.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/paragraph.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/tables.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/flowables.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/**init**.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/frames.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/xpreformatted.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/para.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/doctemplate.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    copying src/reportlab/platypus/paraparser.py -> build/lib.linux-x86_64-2.7/reportlab/platypus
    creating build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/00readme.txt -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/bitstream-vera-license.txt -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/DarkGarden-copying-gpl.txt -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/DarkGarden-copying.txt -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/DarkGarden-readme.txt -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/DarkGarden.sfd -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/DarkGardenMK.afm -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/DarkGardenMK.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/Vera.ttf -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/VeraBd.ttf -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/VeraBI.ttf -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/VeraIt.ttf -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/_abi____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/_ab_____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/_ai_____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/_a______.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/cobo____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/cob_____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/com_____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/coo_____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/_ebi____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/_eb_____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/_ei_____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/fonts/_er_____.pfb -> build/lib.linux-x86_64-2.7/reportlab/fonts
    copying src/reportlab/lib/hyphen.mashed -> build/lib.linux-x86_64-2.7/reportlab/lib
    running build_ext
    building '_rl_accel' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tmp
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab/src
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons/rl_accel
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c /tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons/rl_accel/_rl_accel.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons/rl_accel/_rl_accel.o
    /tmp/pip-build-oEhrNQ/Reportlab/src/rl_addons/rl_accel/_rl_accel.c:11:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
----------------------------------------
```

  Rolling back uninstall of reportlab
Command "/usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-oEhrNQ/Reportlab/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-M6cTeS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-oEhrNQ/Reportlab

a little more of the error just in case that helps

**Comment by dco5** [comment]
Any luck with this?

**Comment by eschipul** [comment]
day job has me talking to clients, which is great as that pays the bills. but haven't set up my vm yet. sorry for the delay. the errors are definitely on us as a good app must be easy to install and set up. I will test it later tonight. #noexcuses

**Comment by dco5** [comment]
Since you mentioned Docker, do you have a docker in Docker Hub or something like that?

**Comment by eschipul** [comment]
@dco5 - I set up vmware using the instructions here:
https://github.com/tendenci/tendenci/blob/master/docs/source/installation/remote.txt

There are some changes I need to get with Jenny on before updating the documentation regarding the uwsgi config, but the dev "python manage.py runserver" works for me. Here are my notes to see if you can check your configuration again?

> ubuntu 14.04.2

sudo apt-get update && sudo apt-get upgrade -yy
sudo apt-get install unattended-upgrades update-notifier-common
sudo dpkg-reconfigure -plow unattended-upgrades
sudo apt-get install gcc make build-essential
sudo apt-get install linux-headers-$(uname -r)
sudo apt-get install openssh-server

> for development only

nano /etc/ssh/sshd_config

> comment out PermitRootLogin without-password
> add PermitRootLogin yes
> restart sshd with
> service ssh restart
> 
> ifconfig to get local IP from vmware - mine is 192.168.184.128

ssh root@192.168.184.128

sudo apt-get update && sudo apt-get upgrade -yy
sudo apt-get install python-software-properties
sudo apt-get install build-essential git python-pip postgresql-9.3 postgresql-contrib-9.3 postgresql-9.3-postgis-2.1 python-dev libevent-dev libpq-dev openssh-server memcached libmemcached-dev libjpeg8 libjpeg-dev libfreetype6 libfreetype6-dev nginx
sudo apt-get update && sudo apt-get upgrade -yy

> skipped DB config here - just be sure to use lowercase for db name, user and password 
> as postgres can be a pain about that if updating files by SED etc...

PROJECT_NAME=tendenci_314159
mkdir -p /opt/webapps/$PROJECT_NAME
cd /opt/webapps/$PROJECT_NAME
django-admin.py startproject --template=https://github.com/tendenci/tendenci-project-template/zipball/tendenci $PROJECT_NAME

> install dependencies

pip install -r requirements/prod.txt
nano /opt/webapps/$PROJECT_NAME/conf/local_settings.py

> next up is editing local_settings.py with database connection information, etc...
> 
> NOTE:  I am betting this is the cause of the problem ---> "sudo apt-get update && sudo apt-get upgrade -yy" <--

**Comment by eschipul** [comment]
@dco5 - as a follow up, I did notice I did one thing differently from the instructions and that was to install "prod.txt" so I went back and repeated it doing a dev install like:

pip install -r requirements/dev.txt

From the root of the site (e.g. cd /var/www/sitename). The above DOES work for me. It gives warnings about not finding files in /addons and /core. That is expected given the old folder structure is deprecated. It does however install all dev or prod packages for me.

I'd like to close this open issue if your config is working now?

**Comment by dco5** [comment]
Ok, so I was able to install it, I do not even how, I had to mix some of your commands, some of the commands in https://github.com/tendenci/tendenci/blob/master/docs/source/installation/remote.txt and some in the https://github.com/tendenci/tendenci/blob/master/docs/source/installation/local.txt and also in the install.md. I think you guys need to have a more concise instructions. I am going to create another virtual environment and try to recreate it again. I will take notes on the steps I use and I can give you guys it if you think that would help.

**Comment by goetzk** [comment]
I know this issue has been closed for a while but i thought I should comment for anyone reading in future.

The docs have had a massive going over and the three files @dco5 mentions are now one - installation/installation.txt (that and other changes are tracked in tendenci/#379). The specific problem you were seeing with python.h missing was because you hadn't installed python-dev, or appropriately versioned python development package.

**Comment by pabloa** [comment]
In Ubuntu 14.04 with virtual environments I used:

from a terminal:

```
sudo apt-get install --yes libpq-dev
sudo pip install psycopg2
```

In the case of manage python virtual environments using intellij, just run apt-get command above and after that install psycopg2.

**Comment by eschipul** [comment]
Reopening as pending as we are now back on pypi as our stable release which should make cleaning up the docs a bit simpler with at least only on stable release out there. Even if under constant dev.

**Comment by eschipul** [comment]
Closing
